#!/usr/bin/env python3
"""
Encrypt benign Chinese-language test payloads for reproducible Trilobyte-style
methodology experiments.

This script is designed to work with payloads generated by
payload_tools/make_test_payloads.py and to reuse the existing cryptographic
helpers in src/crypto.py.

For each input plaintext or compressed payload, it produces:
  - a hidden DAT segment blob: enc || auth
  - a manifest CSV with lengths, hashes, and segment metadata

The goal is not to reproduce the full deployment pipeline, but to support a
reproducible workflow:

  generate payload -> encrypt as Trilobyte DAT segment -> manually inject/upload
  -> download -> verify round-trip integrity / parse later if desired

Examples:
    python payload_tools/encrypt_payloads.py \
        --input-dir examples/sample_payloads/plain \
        --outdir examples/sample_payloads/encrypted_plain \
        --master-key-hex 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff

    python payload_tools/encrypt_payloads.py \
        --input-dir examples/sample_payloads/compressed \
        --outdir examples/sample_payloads/encrypted_compressed \
        --master-key-hex 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff \
        --input-kind compressed

Notes:
  - The same 32-byte master key deterministically derives enc/auth keys.
  - File identifiers (fid) are deterministically derived from filenames unless
    --random-fid is used.
  - Sequence numbers default to 0 and last=True because each input file is
    treated as a single DAT segment in this helper script.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import sys
from pathlib import Path
from typing import Iterable

# Allow imports from the repository root when this script is run directly.
REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.crypto import (  # noqa: E402
    FID_LEN,
    build_dat_hidden_segment,
    derive_trilobyte_keys,
    random_fid,
)


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def parse_master_key_hex(value: str) -> bytes:
    key = bytes.fromhex(value)
    if len(key) != 32:
        raise argparse.ArgumentTypeError(
            f"--master-key-hex must decode to exactly 32 bytes, got {len(key)} bytes"
        )
    return key


def derive_deterministic_fid(name: str) -> bytes:
    """
    Deterministically derive a 16-byte fid from the input filename.
    This is useful for reproducible artifacts.
    """
    digest = hashlib.sha256(name.encode("utf-8")).digest()
    return digest[:FID_LEN]


def collect_input_files(input_dir: Path) -> list[Path]:
    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory does not exist: {input_dir}")
    if not input_dir.is_dir():
        raise NotADirectoryError(f"Input path is not a directory: {input_dir}")

    files = sorted(p for p in input_dir.iterdir() if p.is_file())
    if not files:
        raise FileNotFoundError(f"No files found in input directory: {input_dir}")
    return files


def ensure_outdir(outdir: Path) -> None:
    outdir.mkdir(parents=True, exist_ok=True)


def build_output_name(input_path: Path) -> str:
    return f"{input_path.name}.datseg"


def encrypt_one_file(
    input_path: Path,
    outdir: Path,
    enc_key: bytes,
    auth_key: bytes,
    input_kind: str,
    use_random_fid: bool,
    seq: int,
    last: bool,
) -> dict[str, str | int]:
    payload = input_path.read_bytes()

    fid = random_fid() if use_random_fid else derive_deterministic_fid(input_path.name)
    hidden_blob = build_dat_hidden_segment(
        enc_key=enc_key,
        auth_key=auth_key,
        fid=fid,
        seq=seq,
        last=last,
        data=payload,
    )

    output_name = build_output_name(input_path)
    output_path = outdir / output_name
    output_path.write_bytes(hidden_blob)

    return {
        "input_filename": input_path.name,
        "input_kind": input_kind,
        "input_bytes": len(payload),
        "input_sha256": sha256_hex(payload),
        "output_filename": output_name,
        "output_bytes": len(hidden_blob),
        "output_sha256": sha256_hex(hidden_blob),
        "fid_hex": fid.hex(),
        "seq": seq,
        "last": int(last),
    }


def write_manifest(outdir: Path, rows: Iterable[dict[str, str | int]]) -> Path:
    manifest_path = outdir / "manifest.csv"
    fieldnames = [
        "input_filename",
        "input_kind",
        "input_bytes",
        "input_sha256",
        "output_filename",
        "output_bytes",
        "output_sha256",
        "fid_hex",
        "seq",
        "last",
    ]
    with manifest_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    return manifest_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Encrypt payload files into Trilobyte-style DAT hidden segments."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        required=True,
        help="Directory containing input payload files.",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        required=True,
        help="Directory to write encrypted DAT segment blobs.",
    )
    parser.add_argument(
        "--master-key-hex",
        type=parse_master_key_hex,
        required=True,
        help="32-byte master key encoded as 64 hex characters.",
    )
    parser.add_argument(
        "--input-kind",
        choices=["plain", "compressed", "other"],
        default="plain",
        help="Label recorded in the output manifest.",
    )
    parser.add_argument(
        "--random-fid",
        action="store_true",
        help="Use random fids instead of deterministic filename-derived fids.",
    )
    parser.add_argument(
        "--seq",
        type=int,
        default=0,
        help="Sequence number to place in each DAT segment.",
    )
    parser.add_argument(
        "--not-last",
        action="store_true",
        help="Mark each generated DAT segment as non-final (last=0).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    ensure_outdir(args.outdir)
    input_files = collect_input_files(args.input_dir)

    enc_key, auth_key = derive_trilobyte_keys(args.master_key_hex)
    last = not args.not_last

    rows: list[dict[str, str | int]] = []
    for input_path in input_files:
        row = encrypt_one_file(
            input_path=input_path,
            outdir=args.outdir,
            enc_key=enc_key,
            auth_key=auth_key,
            input_kind=args.input_kind,
            use_random_fid=args.random_fid,
            seq=args.seq,
            last=last,
        )
        rows.append(row)

    manifest_path = write_manifest(args.outdir, rows)

    print(f"[ok] encrypted {len(rows)} payload(s)")
    print(f"[ok] output directory: {args.outdir}")
    print(f"[ok] manifest: {manifest_path}")
    print("[ok] enc/auth keys derived via src.crypto.derive_trilobyte_keys()")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
